name: Publish docs on GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Install dependencies
        run: pip install -r ${GITHUB_WORKSPACE}/requirements.txt

      - name: Setup git repository
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote rm origin
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

      - name: Setup git repository
        run: ~/.local/bin/mkdocs gh-deploy --config-file "${GITHUB_WORKSPACE}/mkdocs.yml" --force
